name: Performance Tests

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v3

      - name: Instalacja Pythona i Locust
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install locust

      - name: Uruchomienie testów Locust
        run: locust -f locustfile.py --headless -u 100 -r 10 -t 5m
