name: Performance Tests

on:
  push:
    branches:
      - main

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v3

      - name: Instalacja JMeter
        run: sudo apt-get install -y jmeter

      - name: Uruchomienie testów JMeter
        run: jmeter -n -t test-plan.jmx -l results.jtl
